{% set version = "1.0.8" %}

package:
  name: jupyterlab_server
  version: {{ version }}

source:
  fn: jupyterlab_server-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-{{ version }}.tar.gz
  sha256: 82aaf337cb5667a4af1c58204f6c6ee9c1193b18fff2a478dc729d0a2c26f30d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools

  run:
    - python >=3.5
    - json5
    - jsonschema >=3.0.1
    - notebook >=4.2.0
    - jinja2 =>2.10

test:
  imports:
    - jupyterlab_server

about:
  home: http://github.com/jupyterlab/jupyterlab_server
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
